package:
  name: pytest
  version: 2.9.2

source:
  fn: pytest-2.9.2.tar.gz
  url: https://pypi.python.org/packages/f0/ee/6e2522c968339dca7d9abfd5e71312abeeb5ee902e09b4daf44f07b2f907/pytest-2.9.2.tar.gz
  md5: b65c2944dfaa0efb62c0239afb424f5b
#  patches:
   # List any patch files here
   # - fix.patch

build:
  entry_points:
    - py.test = pytest:main
  number: 0

requirements:
  build:
    - python
    - pyyaml
    - py

  run:
    - python
    - pyyaml
    - py

about:
  home: http://pytest.org/
  license: MIT license

# See
# https://github.com/ContinuumIO/conda/blob/master/conda/builder/README.txt for
# more information about meta.yaml
