package:
  name: apscheduler
  version: 2.1.1

source:
  fn: APScheduler-2.1.1.tar.gz
  url: https://pypi.python.org/packages/source/A/APScheduler/APScheduler-2.1.1.tar.gz
  md5: e04e2adfdc691ecfd0fafaec36bc2877
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - apscheduler = apscheduler:main
    #
    # Would create an entry point called apscheduler that calls apscheduler.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - distribute

  run:
    - python

test:
  # Python imports
  #imports:
  #  - APScheduler

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://pypi.python.org/pypi/APScheduler/
  license: MIT License

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
