package:
  name: decorator
  version: "4.0.9"

source:
  fn: decorator-4.0.9.tar.gz
  url: https://pypi.python.org/packages/source/d/decorator/decorator-4.0.9.tar.gz
  md5: f12c5651ccd707e12a0abaa4f76cd69a
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - decorator = decorator:main
    #
    # Would create an entry point called decorator that calls decorator.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - decorator

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/micheles/decorator
  license: BSD License
  summary: 'Better living through Python with decorators'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
