package:
  name: pylint-django
  version: 0.7.2

source:
  fn: pylint-django-0.7.2.tar.gz
  url: https://pypi.python.org/packages/ca/dd/128127370cac5fa97136ceaa4f772060fb73c97cce214d5a04c6d4182d16/pylint-django-0.7.2.tar.gz
  md5: 1df4a4d183f34ffa109906609674fb8e

build:
  number: 1

requirements:
  build:
    - python
    - setuptools
    - pylint
    - pylint-plugin-utils
    - astroid

  run:
    - python
    - pylint
    - pylint-plugin-utils
    - astroid

about:
  home: https://github.com/landscapeio/pylint-django
  license: GPLv2

