package:
  name: grafana
  version: 2.1.1

source:
  fn: grafana-2.1.1.linux-x64.tar.gz
  url: https://grafanarel.s3.amazonaws.com/builds/grafana-2.1.1.linux-x64.tar.gz

#  patches:
   # List any patch files here
   # - fix.patch

build:
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - python-memcached = python-memcached:main
    #
    # Would create an entry point called python-memcached that calls python-memcached.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 1

requirements:
  build:
    - system

  run:
    - system

#test:
  # Python imports
  #imports:
  #  - python-memcached

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.
  #  - grafana-server --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://grafana.org
  license: MIT

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
