package:
  name: tempdir
  version: "0.7.1"

source:
  fn: tempdir-0.7.1.tar.gz
  url: https://pypi.python.org/packages/source/t/tempdir/tempdir-0.7.1.tar.gz
  md5: 4076f2d7fa9306c77f7b16a5f2e4c154
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - tempdir = tempdir:main
    #
    # Would create an entry point called tempdir that calls tempdir.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - tempdir

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://bitbucket.org/another_thomas/tempdir
  license: MIT License
  summary: 'Tempdirs are temporary directories, based on tempfile.mkdtemp'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
