package:
  name: pyflakes
  version: 0.9

source:
  fn: pyflakes-0.9.tar.gz
  url: https://pypi.python.org/packages/source/p/pyflakes/pyflakes-0.9.0.tar.gz
  md5: 83472433d0187146708fc52767575eef
#  patches:
   # List any patch files here
   # - fix.patch

build:
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    - pyflakes = pyflakes.api:main
    #
    # Would call pyflakes.api.main()

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0

requirements:
  build:
    - python
    # If setuptools is required to run setup.py, add distribute to the build
    # requirements.
    #
    - distribute
    - setuptools

  run:
    - python
    - distribute
    - setuptools

test:
  # Python imports
  imports:
    - pyflakes

  commands:
    - pyflakes --version
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any test requirements here.  For example
    # - nose

about:
  home: https://launchpad.net/pyflakes
  license: MIT License

# See
# https://github.com/ContinuumIO/conda/blob/master/conda/builder/README.txt for
# more information about meta.yaml
