package:
  name: conda
  version: 1.8.3

source:
  git_url: https://github.com/ContinuumIO/conda.git
  patches:
    - repositories.patch

requirements:
  build:
    - python
    - distribute
    - pycosat

  run:
    - python
    - pycosat
    - yaml
    - pyyaml

build:
  number: 2

about:
  home: https://github.com/ContinuumIO/conda
  license: BSD
