package:
  name: numba
  version: 0.22.1

source:
  git_url: https://github.com/numba/numba.git


requirements:
  build:
    - distribute
    - python
    #- llvmpy
    #- llvmmath
    - numpy
    - cython
    - meta
    #- cffi
    - funcsigs
    - llvm-lite
    - enum34

  run:
    - python
    #- llvmpy
    #- llvmmath
    - numpy
    - cython
    #- meta
    #- cffi
    - funcsigs
    - llvm-lite
    - enum34


build:
  number: 0


about:
  home: http://numba.pydata.org
  license: PSF
