package:
  name: llvmlite
  version: "0.9.0"

source:
  git_url: https://github.com/numba/llvmlite.git


#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - funcsigs = funcsigs:main
    #
    # Would create an entry point called funcsigs that calls funcsigs.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - enum34
    - llvm

  run:
    - python
    - enum34
    - llvm

test:
  # Python imports
  imports:
    - llvmlite

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    - unittest2
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://funcsigs.readthedocs.org
  license: Apache Software License
  summary: 'Python function signatures from PEP362 for Python 2.6, 2.7 and 3.2+'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
