package:
  name: django-tagging
  version: !!str 0.3.2

source:
  fn: django-tagging-0.3.2.tar.gz
  url: https://pypi.python.org/packages/source/d/django-tagging/django-tagging-0.3.2.tar.gz
  md5: 23d4040f1d5e50511c9bc94565bf4baa
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - django-tagging = django-tagging:main
    #
    # Would create an entry point called django-tagging that calls django-tagging.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python

  run:
    - python
    - django

test:
  # Python imports
  #imports:
  #  - tagging
  #  - tagging.templatetags
  #  - tagging.tests

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  #requires:
  #  # Put any additional test requirements here.  For example
  #  - nose


about:
  home: https://code.google.com/p/django-tagging/
  license: BSD License
  summary: 'Generic tagging application for Django'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
