package:
  name: msgpack-pure
  version: !!str 0.1.3

source:
  fn: msgpack-pure-0.1.3.tar.gz
  url: https://pypi.python.org/packages/source/m/msgpack-pure/msgpack-pure-0.1.3.tar.gz
  md5: 4fc0fbb334db82b2079141034ccd91ae
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - msgpack-pure = msgpack-pure:main
    #
    # Would create an entry point called msgpack-pure that calls msgpack-pure.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - msgpack_pure

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://msgpack.org/
  license: ache Software License
  summary: 'MessagePack (de)serializer written in pure Python.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
