#!/bin/bash
set -e
echo "Running installer..."

DEFAULT_TARGET=/opt/foo


echo -n "Installing to [$DEFAULT_TARGET]: "
read TARGET

if [ "$TARGET" = "" ]
then
  TARGET=$DEFAULT_TARGET
fi

echo tar x -f files.tar -C $TARGET
