package:
  name: blist
  version: "1.3.6"

source:
  fn: blist-1.3.6.tar.gz
  url: https://pypi.python.org/packages/source/b/blist/blist-1.3.6.tar.gz
  md5: a538f1a24b9191e3c40252e9397408a9
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - blist = blist:main
    #
    # Would create an entry point called blist that calls blist.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - blist

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://stutzbachenterprises.com/blist/
  license: BSD License
  summary: 'a list-like type with better asymptotic performance and similar performance on small lists'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
