package:
  name: ujson
  version: !!str 1.33

source:
  fn: ujson-1.33.zip
  url: https://pypi.python.org/packages/source/u/ujson/ujson-1.33.zip
  md5: 8148a2493fff78940feab1e11dc0a893
  patches:
    # List any patch files here
    - ujson-1.33-nan.patch

build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - ujson = ujson:main
    #
    # Would create an entry point called ujson that calls ujson.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - ujson

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://www.esn.me
  license: BSD License

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
