package:
  name: lockfile
  version: !!str 0.9.1

source:
  fn: lockfile-0.9.1.tar.gz
  url: https://pypi.python.org/packages/source/l/lockfile/lockfile-0.9.1.tar.gz
  md5: ce61468d4c1263e3005737bbed2641f0
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - lockfile = lockfile:main
    #
    # Would create an entry point called lockfile that calls lockfile.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python

  run:
    - python

test:
  # Python imports
  imports:
    - lockfile

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://code.google.com/p/pylockfile/
  license: MIT License
  summary: 'Platform-independent file locking module'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
