package:
  name: auxlib
  version: "0.0.36"

source:
  fn: auxlib-0.0.36.tar.gz
  url: https://pypi.python.org/packages/5f/8d/0caac9d1c65d70c3b9485d6306f74a8cee9adfa0c97c943cb50b35f1649d/auxlib-0.0.36.tar.gz
  md5: b91651036f21ed0d1aaa15ecd2192f3d
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - auxlib = auxlib:main
    #
    # Would create an entry point called auxlib that calls auxlib.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - dateutil
    - pyyaml
    - enum34

  run:
    - python
    - dateutil
    - pyyaml
    - enum34

test:
  # Python imports
  imports:
    - auxlib
    - auxlib._vendor

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/kalefranz/auxlib
  license: Apache Software License or BSD License
  summary: 'auxiliary library to the python standard library'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
