package:
  name: htop
  version: 2.0.0

source:
  fn : htop-2.0.0.tar.gz
  url: http://hisham.hm/htop/releases/2.0.0/htop-2.0.0.tar.gz

requirements:
  build:
    - ncurses
  run:
    - ncurses

about:
  home: http://htop.sourceforge.net
  license: BSD
