package:
  name: scipy
  version: 0.14.1

source:
  url: https://pypi.python.org/packages/source/s/scipy/scipy-0.14.1.tar.gz
  fn: scipy-0.14.1.tar.gz

requirements:
  build:
    - system
    - python
    - numpy
    #- blas
    #- lapack
    #- atlas
    - openblas

  run:
    - numpy
    - openblas

build:
  number: 0

about:
  home: https://www.scipy.org
  license: PSF
