package:
  name: certifi
  version: 2016.2.28

source:
  fn: certifi-2016.2.28.tar.gz
  url: https://pypi.python.org/packages/source/c/certifi/certifi-2016.2.28.tar.gz
  md5: 5d672aa766e1f773c75cfeccd02d3650

build:
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - certifi

about:
  home: http://certifi.io/
  license: ISC
