package:
  name: redis-server
  version: 2.8.19

source:
  fn: redis-2.8.19.tar.gz
  url: http://download.redis.io/releases/redis-2.8.19.tar.gz
#  patches:
   # List any patch files here
   # - fix.patch

build:
  detect_binary_files_with_prefix: true
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - redis = redis:main
    #
    # Would create an entry point called redis that calls redis.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 2

requirements:
  build:
    - system

  run:
    - system

test:
  # Python imports
  #imports:
  #  - redis

  commands:
  #  # You can put test commands to be run here.  Use this to test that the
  #  # entry points work.
    - redis-cli --version

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://www.redis.io
  license: Unknown
  summary: 'redis server'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
