package:
  name: shutilwhich
  version: "1.1.0"

source:
  fn: shutilwhich-1.1.0.tar.gz
  url: https://pypi.python.org/packages/source/s/shutilwhich/shutilwhich-1.1.0.tar.gz
  md5: 915947c5cdae7afd748ac715ee547adb
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - shutilwhich = shutilwhich:main
    #
    # Would create an entry point called shutilwhich that calls shutilwhich.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - shutilwhich

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/mbr/shutilwhich
  license: PSF
  summary: 'shutil.which for those not using Python 3.3 yet.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
