package:
  name: matplotlib
  version: 1.5.0

source:
  url: https://pypi.python.org/packages/source/m/matplotlib/matplotlib-1.5.0.tar.gz
  fn: matplotlib-1.5.0.tar.gz

requirements:
  build:
    - python
    - numpy
    - freetype
    - bzip2
    - dateutil
    - pyparsing
    - six
    - libpng
    - nose
    - setuptools
    - distribute

  run:
    - python
    - numpy
    - freetype
    - bzip2
    - dateutil
    - pyparsing
    - six
    - libpng
    - pillow
    - pytz


build:
  number: 0

about:
  home: http://www.matplotlib.org
  license: BSD
