package:
  name: yapf
  version: 0.2.3

source:
  git_url: https://github.com/google/yapf
  patches:
    - argv.patch
  
build:
  entry_points:
    - yapf = yapf:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 4

requirements:
  build:
    - python
    # If setuptools is required to run setup.py, add distribute to the build
    # requirements.
    #
    - distribute
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - yapf

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any test requirements here.  For example
    # - nose

about:
  home: https://github.com/google/yapf
  license: BSD
