package:
  name: etcd
  version: 2.0.0

source:
  fn : etcd-v2.0.0-linux-amd64.tar.gz
  url: https://github.com/coreos/etcd/releases/download/v2.0.0/etcd-v2.0.0-linux-amd64.tar.gz

requirements:
#  build:
#    - 
#  run:
#    - 

build:
  number: 0

about:
  home: https://github.com/coreos/etcd/
  license: BSD
