package:
  name: scikit-learn
  version: 0.17.1

source:
  fn: scikit-learn-0.17.1.tar.gz
  url: https://pypi.python.org/packages/source/s/scikit-learn/scikit-learn-0.17.1.tar.gz
  md5: a2f8b877e6d99b1ed737144f5a478dfc
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - scikit-learn = scikit-learn:main
    #
    # Would create an entry point called scikit-learn that calls scikit-learn.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - numpy
    - scipy
    - setuptools

  run:
    - python
    - numpy
    - scipy


test:
  # Python imports
  imports:
    - sklearn

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://scikit-learn.org
  license: BSD License
  summary: 'machine learning for SciPy'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
