package:
  name: python
  version: 2.7.11

source:
  fn: Python-2.7.11.tar.gz
  url: https://www.python.org/ftp/python/2.7.11/Python-2.7.11.tgz


requirements:
  build:
     - openssl
     - readline
     - sqlite
     - system
     - zlib
     - bzip2
  run:
     - openssl
     - readline
     - sqlite
     - system
     - zlib
     - bzip2


build:
  number: 1


about:
  home: http://www.python.org
  license: PSF
