package:
  name: pip
  version: 7.1.2

source:
  url: https://pypi.python.org/packages/source/p/pip/pip-7.1.2.tar.gz
  fn: pip-7.1.2.tar.gz

requirements:
  build:
    - python
    #- distribute
    #- setuptools

  run:
    - python
    #- distribute
    #- setuptools
    
build:
  #preserve_egg_dir: True
  number: 0
  entry_points:
    #- pip = pip.runner:run
    - pip = pip:main


about:
  home: https://pip.pypa.io
  license: PSF
