package:
  name: pygrib
  #version: 1.9.9
  version: 1.9.9

source:
  fn: pygrib-1.9.9.tar.gz		
  url: https://pypi.python.org/packages/source/p/pygrib/pygrib-1.9.9.tar.gz
  patches:
   - voidp.patch

requirements:
  build:
    - python
    - numpy    
    - pyproj
    - gribapi
  run:
    - gribapi
    - python
    - numpy    
    - pyproj

build:
  number: 0

about:
  home: https://software.ecmwf.int/wiki/display/GRIB/Home
  license: Apache
