package:
  name: pandas
  version: 0.11.0

source:
  fn: pandas-0.11.0.tar.gz
  url: https://pypi.python.org/packages/source/p/pandas/pandas-0.11.0.tar.gz
  md5: 5d95cb31c113bc27b9de96e8fbd480cb
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pandas:main
    #
    # Would call pandas.main()

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - cython
    - scipy
    - pytz
    # If setuptools is required to run setup.py, add distribute to the build
    # requirements.
    #
    # - distribute

  run:
    - python
    - numpy
    - scipy
    - pytz
    # - matplotlib
    # - statsmodels
    # - pytables
    # - openpyxl

test:
  # Python imports
  imports:
    - pandas

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any test requirements here.  For example
    # - nose

about:
  home: http://pandas.pydata.org
  license: BSD

# See
# https://github.com/ContinuumIO/conda/blob/master/conda/builder/README.txt for
# more information about meta.yaml
