package:
  name: wmctrl
  version: "0.3"

source:
  fn: wmctrl-0.3.tar.gz
  url: https://pypi.python.org/packages/source/w/wmctrl/wmctrl-0.3.tar.gz
  md5: 3a3f45e240f1f375950da32315c841bb
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - wmctrl = wmctrl:main
    #
    # Would create an entry point called wmctrl that calls wmctrl.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - wmctrl

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://bitbucket.org/antocuni/wmctrl
  license: BSD
  summary: 'A tool to programmatically control windows inside X'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
