package:
  name: conda-build
  version: 2.4.18

source:
  git_url: https://github.com/conda/conda-build.git
  patches:
    - ignore_dot_svn.patch

requirements:
  build:
    - python
    - distribute
    - pycosat
    - patchelf
    - requests

  run:
    - python
    - pycosat
    - yaml
    - pyyaml
    - patchelf
    - distribute
    - setuptools


build:
  number: 0

about:
  home: https://github.com/ContinuumIO/conda
  license: BSD
