package:
  name: pylint
  version: 1.0

source:
  fn: pylint-0.28.0.tar.gz
  url: https://pypi.python.org/packages/source/p/pylint/pylint-0.28.0.tar.gz
  md5: 1ccd3812c2729b605e5fd9425ef376e6
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pylint:main
    #
    # Would call pylint.main()

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    # If setuptools is required to run setup.py, add distribute to the build
    # requirements.
    #
    # - distribute

  run:
    - python
    - astroid
    - logilab-common

test:
  # Python imports
  imports:
    - pylint

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any test requirements here.  For example
    # - nose

about:
  home: http://www.pylint.org
  license: GPL

# See
# https://github.com/ContinuumIO/conda/blob/master/conda/builder/README.txt for
# more information about meta.yaml
