package:
  name: wdfs
  version: 1.4.2

source:
  git_url: https://github.com/jmesmon/wdfs.git

requirements:
  build:
    - libfuse
    - glib
    - neon
  run:
    - libfuse
    - glib
    - neon

about:
  home: https://github.com/rpodgorny/unionfs-fuse
  license: GPL
