package:
  name: tables
  version: 3.1.1

source:
  fn: tables-3.1.1.tar.gz
  url: https://pypi.python.org/packages/source/t/tables/tables-3.1.1.tar.gz

#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - tables = tables:main
    #
    # Would create an entry point called tables that calls tables.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - distribute
    - setuptools
    - numpy
    - hdf5
    - bzip2
    - zlib
    - numexpr
    - cython
    
  run:
    - python
    - numpy
    - hdf5
    - bzip2
    - zlib
    - numexpr

test:
  # Python imports
  imports:
    - tables

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://www.pytables.org/
  license: BSD License

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
