package:
  name: proot
  version: 5.1.0

source:
  git_url: https://github.com/cedric-vincent/PRoot.git

requirements:
  build:
    - libtalloc
  run:
    - libtalloc

about:
  home: http://www.proot.me
  license: BSD
