package:
  name: pysay
  version: 2.0.0

source:
  git_url: https://github.com/nicolalamacchia/pysay.git
#  patches:
   # List any patch files here
   # - fix.patch

build:
  preserve_egg_dir: False
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pyparsing = pyparsing:main
    #
    # Would create an entry point called pyparsing that calls pyparsing.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python

  run:
    - python

test:
  # Python imports
  #imports:
  #  - pysay

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/nicolalamacchia/pysay
  license: MIT License
  summary: 'cowsay in Python'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
