package:
  name: neon
  version: 0.30.1

source:
  fn: neon-0.30.1.tar.gz
  url: http://www.webdav.org/neon/neon-0.30.1.tar.gz

requirements:
  build:
    - openssl
    - libxml2
  run:
    - openssl
    - libxml2

about:
  home: http://www.webdav.org/neon/
  license: LGPL
