package:
  name: pyopengl
  version: 3.0.1

source:
  fn: PyOpenGL-3.0.1.tar.gz
  url: https://pypi.python.org/packages/source/P/PyOpenGL/PyOpenGL-3.0.1.tar.gz
  md5: cdf03284f24279b8d9914bb680a37b5e
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pyopengl = pyopengl:main
    #
    # Would create an entry point called pyopengl that calls pyopengl.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python

  run:
    - python

test:
  # Python imports
  imports:
    - PyOpenGL

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://pyopengl.sourceforge.net
  license: BSD License

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
