package:
  name: futures
  version: "3.0.3"

source:
  fn: futures-3.0.3.tar.gz
  url: https://pypi.python.org/packages/source/f/futures/futures-3.0.3.tar.gz
  md5: 32171f72af7e80c266310794adc4db46

#  patches:
   # List any patch files here
   # - fix.patch

build:
  preserve_egg_dir: False
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - futures = futures:main
    #
    # Would create an entry point called futures that calls futures.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - concurrent
    - concurrent.futures
    #- futures

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://code.google.com/p/pythonfutures
  license: BSD License
  summary: 'Backport of the concurrent.futures package from Python 3.2'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
