package:
  name: pyqtgraph
  version: 0.9.10

source:
  fn: pyqtgraph-0.9.10.tar.gz
  url: https://pypi.python.org/packages/source/p/pyqtgraph/pyqtgraph-0.9.10.tar.gz


requirements:
  build:
    - python
    - numpy
    - scipy

  run:
    - pyqt
    - python
    - numpy
    - scipy

test:
  imports:
    - pyqtgraph

about:
  home: http://www.pyqtgraph.org
  license: MIT License
