package:
  name: zope.interface
  version: !!str 4.1.1

source:
  fn: zope.interface-4.1.1.tar.gz
  url: https://pypi.python.org/packages/source/z/zope.interface/zope.interface-4.1.1.tar.gz
  md5: edcd5f719c5eb2e18894c4d06e29b6c6
#  patches:
   # List any patch files here
   # - fix.patch

build:
  preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - zope.interface = zope.interface:main
    #
    # Would create an entry point called zope.interface that calls zope.interface.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools

test:
  # Python imports
  imports:
    - zope
    - zope.interface
    - zope.interface.tests

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://pypi.python.org/pypi/zope.interface
  license: Zope Public License
  summary: 'Interfaces for Python'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
