#!/bin/bash
cd payload
tar cf ../payload.tar ./*
cd ..

if [ -e "payload.tar" ]; then
    gzip payload.tar
    
    if [ -e "payload.tar.gz" ]; then
       cat decompress payload.tar.gz > installer-foo.sh
       chmod +x installer-foo.sh
       exit 0
    else
       echo "payload.tar.gz does not exist"
       exit 1
    fi
else
    echo "payload.tar does not exist"
    exit 1
fi
